### ISSUE TITLE
Multiple languages

### ISSUE THREAD

**Issue by Pinkeltje** [conseilgouz/pkg_automsg_j4#1]
Tried your French version and I think its perfect. Are you planning to add more languages. Especially interested in Dutch. Can do translations for you, like I did for AutoReadMore Extension.

**Comment by conseilgouz** [comment]
Thank you for your message.
I'll appreciate your help on dutch language.
I'm working on the english language files.
This package was not supposed to be international. It was done from a french customer request.
It's now using more Joomla features : task and mail template, so it makes more sense to go to international.
Kind regards,
Pascal

**Comment by conseilgouz** [comment]
Hi Astrid,
I just released english language files and I cleaned up the french one.
Regards,
Pascal

**Comment by conseilgouz** [comment]
FYI, version 4.2.0 includes new fields to translate...
Pascal

**Comment by Pinkeltje** [comment]
Hi Pascal,
While translating, I found two texts still hard coded in the php files:

Un article par message
Erreurs
![2024-06-10 Screenshot 417](https://github.com/conseilgouz/pkg_automsg_j4/assets/8941310/757cdb72-fa66-4ada-928f-11bcf49e9ee2)

**Comment by conseilgouz** [comment]
Thank you for telling me, I'll fix this as soon as possible. 
New values are COM_AUTOMSG_ASYNC_ONE and COM_AUTOMSG_LOG_ERRORS
Pascal

**Comment by conseilgouz** [comment]
Hello Astrid, 

4.2.4 version fixes missing values.

Pascal

**Comment by Pinkeltje** [comment]
Yes, but still missing in forms/config.xml
`        <field name="log"
            type="radio" class="btn-group btn-group-yesno" default="0"
            label="COM_AUTOMSG_LOG" description="COM_AUTOMSG_LOG_DESC">
            <option value="0">JNO</option>
            <option value="1">JERRORS</option>
            <option value="21">JALL</option>
        </field>`

**Comment by conseilgouz** [comment]
close with pr #2 (thank you Astrid)
and version 4.2.5
