### ISSUE TITLE
Small cosmetic improvements

### ISSUE THREAD

**Issue by Pinkeltje** [conseilgouz/pkg_automsg_j4#7]
Hi Pascal,

Extension works like a charm! But I've notice a small cosmetic imperfection with a.o. the confirmation page after saving preferences.
![2024-06-18 Screenshot 455](https://github.com/conseilgouz/pkg_automsg_j4/assets/8941310/6bf86376-6dde-4a9a-966d-503cbf0df4ec)
example from complete.php (there are more occurrences).
`<div class="col-md-4" style="margin-top:1em"><a href="index.php"  rel="noopener noreferrer"><button><?php echo Text::_('COM_AUTOMSG_HOME');?></button></a></div>` 
No hurry as I already made an override of the file.
![2024-06-18 Screenshot 456](https://github.com/conseilgouz/pkg_automsg_j4/assets/8941310/d47e991b-d4d1-4a7b-bcf6-f82330494d5b)
Should be something like this I think:
`<div class="col-md-4" style="margin-top:1em"><a class="btn btn-primary" href="index.php" rel="noopener noreferrer"><?php echo Text::_('COM_AUTOMSG_HOME');?></a>`

Cordialement,
Astrid`

**Comment by conseilgouz** [comment]
Hi Astrid,
Thank you for reporting this.
New version 4.2.11 fixes it.
Kind regards,
Pascal
